/* ---------------------------------------------------- */
/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-dets-2017 14:31:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */


/* Drop Tables */

DROP TABLE IF EXISTS Isik CASCADE
;

DROP TABLE IF EXISTS Kaup CASCADE
;

DROP TABLE IF EXISTS Kauba_kategooria_omamine CASCADE
;

DROP TABLE IF EXISTS Tootaja_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Riik CASCADE
;

DROP TABLE IF EXISTS Varv_Kaup CASCADE
;

DROP TABLE IF EXISTS Varv CASCADE
;

DROP TABLE IF EXISTS Tyyp CASCADE
;

DROP TABLE IF EXISTS Suurus CASCADE
;

DROP TABLE IF EXISTS Materjal CASCADE
;

DROP TABLE IF EXISTS Kliendi_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Kauba_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Kauba_kategooria_tyyp CASCADE
;

DROP TABLE IF EXISTS Kauba_kategooria CASCADE
;

DROP TABLE IF EXISTS Isiku_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Amet CASCADE
;

DROP TABLE IF EXISTS Klient CASCADE
;

DROP TABLE IF EXISTS Tootaja CASCADE
;



CREATE TABLE Riik
(
	riigi_kood varchar(3)	 NOT NULL,
	riigi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Riik PRIMARY KEY (riigi_kood),
	CONSTRAINT unique_riik_nimetus UNIQUE (riigi_nimetus),
	CONSTRAINT check_riigi_nimetus_not_empty CHECK (riigi_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT check_riigi_kood_has_three_letters CHECK (riigi_kood~'^[A-Z]{3}$')
)
;

CREATE TABLE Amet
(
	ameti_kood varchar(12)	 NOT NULL,
	ameti_nimetus varchar(255)	 NOT NULL,
	ameti_kirjeldus varchar(1000)	 NULL,
	CONSTRAINT PK_Amet PRIMARY KEY (ameti_kood),
	CONSTRAINT unique_amet_nimetus UNIQUE (ameti_nimetus),
	CONSTRAINT check_ameti_kirjeldus CHECK (ameti_kirjeldus!~'^[[:space:]]*$'),
	CONSTRAINT check_ameti_nimetus CHECK (ameti_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT check_ameti_kood CHECK (ameti_kood!~'^[[:space:]]*$')
)
;

CREATE TABLE Varv
(
	varvi_kood varchar(12)	 NOT NULL,
	varvi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Varv PRIMARY KEY (varvi_kood),
	CONSTRAINT unique_varv_nimetus UNIQUE (varvi_nimetus),
	CONSTRAINT varvi_kood CHECK (varvi_kood!~'^[[:space:]]*$'),
	CONSTRAINT varvi_nimetus CHECK (varvi_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Tyyp
(
	tyybi_kood varchar(12)	 NOT NULL,
	tyybi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Tyyp PRIMARY KEY (tyybi_kood),
	CONSTRAINT unique_tyyp_nimetus UNIQUE (tyybi_nimetus),
	CONSTRAINT check_tyybi_kood CHECK (tyybi_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_tyybi_nimetus CHECK (tyybi_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Suurus
(
	suuruse_kood varchar(12)	 NOT NULL,
	suuruse_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Suurus PRIMARY KEY (suuruse_kood),
	CONSTRAINT unique_suurus_nimetus UNIQUE (suuruse_nimetus),
	CONSTRAINT check_suuruse_kood CHECK (suuruse_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_suuruse_nimetus CHECK (suuruse_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Materjal
(
	materjali_kood varchar(12)	 NOT NULL,
	materjali_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Materjal PRIMARY KEY (materjali_kood),
	CONSTRAINT unique_materjal_nimetus UNIQUE (materjali_nimetus),
	CONSTRAINT check_materjali_nimetus CHECK (materjali_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT check_materjali_kood CHECK (materjali_kood!~'^[[:space:]]*$')
)
;

CREATE TABLE Isiku_seisundi_liik
(
	isiku_seisundi_liigi_kood varchar(12)	 NOT NULL,
	isiku_seisundi_liigi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Isiku_seisundi_liik PRIMARY KEY (isiku_seisundi_liigi_kood),
	CONSTRAINT unique_isiku_seisundi_liik_nimetus UNIQUE (isiku_seisundi_liigi_nimetus),
	CONSTRAINT check_isiku_seisundi_liigi_kood CHECK (isiku_seisundi_liigi_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_isiku_seisundi_liigi_nimetus CHECK (isiku_seisundi_liigi_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Kliendi_seisundi_liik
(
	kliendi_seisundi_liigi_kood varchar(12)	 NOT NULL,
	kliendi_seisundi_liigi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Kliendi_seisundi_liik PRIMARY KEY (kliendi_seisundi_liigi_kood),
	CONSTRAINT unique_kliendi_seisundi_liik_nimetus UNIQUE (kliendi_seisundi_liigi_nimetus),
	CONSTRAINT check_kliendi_seisundi_liigi_kood CHECK (kliendi_seisundi_liigi_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_kliendi_seisundi_liigi_nimetus CHECK (kliendi_seisundi_liigi_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Tootaja_seisundi_liik
(
	tootaja_seisund_liigi_kood varchar(12)	 NOT NULL,
	tootaja_seisundi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Tootaja_seisundi_liik PRIMARY KEY (tootaja_seisund_liigi_kood),
	CONSTRAINT unique_tootaja_seisundi_liik_nimetus UNIQUE (tootaja_seisundi_nimetus),
	CONSTRAINT check_tootaja_seisundi_liigi_kood CHECK (tootaja_seisund_liigi_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_tootaja_seisundi_liigi_nimetus CHECK (tootaja_seisundi_nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Kauba_seisundi_liik
(
	kauba_seisundi_liigi_kood varchar(12)	 NOT NULL,
	kauba_seisundi_liigi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Kauba_seisundi_liik PRIMARY KEY (kauba_seisundi_liigi_kood),
	CONSTRAINT unique_kauba_seisundi_liik_nimetus UNIQUE (kauba_seisundi_liigi_nimetus),
	CONSTRAINT check_kauba_seisundi_liigi_nimetus CHECK (kauba_seisundi_liigi_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT check_kauba_seisundi_liigi_kood CHECK (kauba_seisundi_liigi_kood!~'^[[:space:]]*$')
)
;

CREATE TABLE Kauba_kategooria_tyyp
(
	kategooria_tyybi_kood varchar(12)	 NOT NULL,
	kategooria_tyybi_nimetus varchar(255)	 NOT NULL,
	CONSTRAINT PK_Kauba_kategooria_tyyp PRIMARY KEY (kategooria_tyybi_kood),
	CONSTRAINT unique_kauba_kategooria_tyyp_nimetus UNIQUE (kategooria_tyybi_nimetus),
	CONSTRAINT check_kauba_kategooria_nimetus CHECK (kategooria_tyybi_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT check_kauba_kategooria_kood CHECK (kategooria_tyybi_kood!~'^[[:space:]]*$')
)
;

CREATE TABLE Isik
(
	isik_id serial NOT NULL,
	isiku_seisundi_liigi_kood varchar(12) NOT NULL,
	isikukoodi_riik varchar(3)	 NOT NULL,
	isikukood varchar(50)	 NOT NULL,
	eesnimi varchar(1200)	 NOT NULL,
	parool varchar(32)	 NOT NULL,
	e_mail varchar(254)	 NOT NULL,
	synni_kp date NOT NULL,
	reg_aeg timestamp NOT NULL DEFAULT localtimestamp,
	perenimi varchar(1200)	 NULL,
	elukoht varchar(255)	 NULL,
	CONSTRAINT PK_Isik PRIMARY KEY (isik_id),
	CONSTRAINT FK_Isik_isiku_seisundi_liik FOREIGN KEY (isiku_seisundi_liigi_kood) REFERENCES Isiku_seisundi_liik (isiku_seisundi_liigi_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Isik_isikukoodi_riik FOREIGN KEY (isikukoodi_riik) REFERENCES Riik (riigi_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT unique_isik_isikukood UNIQUE (isikukood, isikukoodi_riik),
	CONSTRAINT unique_isik_e_mail UNIQUE (e_mail),
	CONSTRAINT check_isik_reg_aeg CHECK (reg_aeg BETWEEN '2010-01-01 00:00:00' AND '2100-12-31 23:59:59'),
	CONSTRAINT check_isik_synni_kp CHECK (synni_kp BETWEEN '1900-01-01' AND '2100-12-31'),
	CONSTRAINT check_isik_email CHECK (e_mail~'^(.*@.*[.].*)$'),
	CONSTRAINT check_isik_eesnimi CHECK (eesnimi!~'^[[:space:]]*$'),
	CONSTRAINT check_isik_elukoht_mitte_tyhi_string CHECK (elukoht!~'^[[:space:]]*$'),
	CONSTRAINT check_isik_elukoht_ei_sisalda_ainult_numbreid CHECK (elukoht !~'^([[:digit:]])*$'),
	CONSTRAINT check_parooli_rasi CHECK (parool~'^[a-zA-Z0-9]{60}$'),
	CONSTRAINT check_isik_perenimi CHECK (perenimi!~'^[[:space:]]*$'),
	CONSTRAINT check_isikukood_mitte_tyhi_string CHECK (isikukood!~'^[[:space:]]*$'),
	CONSTRAINT check_isikukood_eesti CHECK (NOT (isikukoodi_riik='EST') OR isikukood~'^([3-6]{1}[[:digit:]]{2}[0-1]{1}[[:digit:]]{1}[0-3]{1}[[:digit:]]{5})$')
)
;

CREATE TABLE Klient
(
	isik_id Integer NOT NULL,
	kliendi_seisundi_kood varchar(12)	 NOT NULL,
	on_nous_tylitamisega boolean NULL DEFAULT false,
	CONSTRAINT PK_Klient PRIMARY KEY (isik_id),
	CONSTRAINT FK_Klient_Kliendi_seisundi_liik FOREIGN KEY (kliendi_seisundi_kood) REFERENCES Kliendi_seisundi_liik (kliendi_seisundi_liigi_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Klient_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE CASCADE ON UPDATE CASCADE
)
;

CREATE TABLE Tootaja
(
	isik_id Integer NOT NULL,
	seisundi_liigi_kood varchar(12)	 NOT NULL,
	ameti_kood varchar(12)	 NOT NULL,
	CONSTRAINT PK_Tootaja PRIMARY KEY (isik_id),
	CONSTRAINT FK_Tootaja_Amet FOREIGN KEY (ameti_kood) REFERENCES Amet (ameti_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Tootaja_Tootaja_seisundi_liik FOREIGN KEY (isik_id) REFERENCES Tootaja_seisundi_liik (tootaja_seisund_liigi_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Tootaja_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE CASCADE ON UPDATE CASCADE
)
;

CREATE TABLE Kauba_kategooria
(
	kauba_kategooria_kood varchar(12)	 NOT NULL,
	kauba_kategooria_nimetus varchar(255)	 NOT NULL,
	kauba_kategooria_tyybi_kood varchar(12)	 NOT NULL,
	CONSTRAINT PK_Kauba_kategooria PRIMARY KEY (kauba_kategooria),
	CONSTRAINT unique_kauba_kategooria UNIQUE (kauba_kategooria_kood),
	CONSTRAINT check_kategooria_kood CHECK (kauba_kategooria_kood!~'^[[:space:]]*$'),
	CONSTRAINT check_kategooria_nimetus CHECK (kauba_kategooria_nimetus!~'^[[:space:]]*$'),
	CONSTRAINT FK_Kauba_kategooria_Kauba_kategooria_tyyp FOREIGN KEY (kauba_kategooria_tyybi_kood) REFERENCES Kauba_kategooria_tyyp (kategooria_tyybi_kood) ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE Kaup
(
	kauba_kood varchar(12) NOT NULL,
	kauba_nimetus varchar(50)	 NOT NULL,
	kauba_kirjeldus varchar(1000)	 NOT NULL,
	hind decimal(6,2) NOT NULL,
	kauba_kategooria_tyyp varchar(12)	 NOT NULL,
	kauba_seisundi_liigi_kood varchar(12) NOT NULL,
	registreerija_id Integer NOT NULL,
	kauba_reg_aeg timestamp NOT NULL DEFAULT localtimestamp(0),
	palli_materjali_kood varchar(12)	 NOT NULL,
	palli_varvi_kood varchar(12)	 NOT NULL,
	palli_tyybi_kood varchar(12)	 NOT NULL,
	palli_suuruse_kood varchar(12)	 NOT NULL,
	CONSTRAINT PK_Kaup PRIMARY KEY (kauba_kood),
	CONSTRAINT unique_kaup_nimetus UNIQUE (kauba_nimetus),
	CONSTRAINT check_kaup_kauba_reg_aeg CHECK (kauba_reg_aeg BETWEEN '2010-01-01 00:00:00' AND '2100-12-31 23:59:59'),
	CONSTRAINT check_hind CHECK (hind > 0),
	CONSTRAINT check_kauba_nimetus_not_empty CHECK (kauba_nimetus !~'^[[:space:]]*$'),
	CONSTRAINT FK_Kaup_Kauba_seisundi_liik FOREIGN KEY (kauba_seisundi_liigi_kood) REFERENCES Kauba_seisundi_liik (kauba_seisundi_liigi_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kaup_Kauba_kategooria_tyyp FOREIGN KEY (kauba_kategooria_tyyp) REFERENCES Kauba_kategooria (kauba_kategooria_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kaup_Tootaja FOREIGN KEY (registreerija_id) REFERENCES Tootaja (isik_id) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kaup_Palli_materjal FOREIGN KEY (palli_materjali_kood) REFERENCES Materjal (materjali_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kaup_Palli_suurus FOREIGN KEY (palli_suuruse_kood) REFERENCES Suurus (suuruse_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kaup_Palli_tyyp FOREIGN KEY (palli_tyybi_kood) REFERENCES Tyyp (tyybi_kood) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_Kaup_Palli_varv FOREIGN KEY (palli_varvi_kood) REFERENCES Varv (varvi_kood) ON DELETE CASCADE ON UPDATE CASCADE
)
;

CREATE TABLE Varv_Kaup
(
	varvi_kood varchar(12)	 NOT NULL,
	kauba_kood varchar(12)	 NOT NULL,
	CONSTRAINT PK_Varv_Kaup PRIMARY KEY (varvi_kood,kauba_kood),
	CONSTRAINT FK_Varv_Kaup_Kaup FOREIGN KEY (kauba_kood) REFERENCES Kaup (kauba_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Varv_Kaup_Varv FOREIGN KEY (varvi_kood) REFERENCES Varv (varvi_kood) ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE Kauba_kategooria_omamine
(
	kauba_kood varchar(12) NOT NULL,
	kauba_kategooria_kood varchar(12)	 NOT NULL,
	CONSTRAINT PK_Kauba_kategooria_omamine PRIMARY KEY (kauba_kood),
	CONSTRAINT FK_Kauba_kategooria_omamine_Kaup FOREIGN KEY (kauba_kood) REFERENCES Kaup (kauba_kood) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Kauba_kategooria_omamine_Kauba_kategooria FOREIGN KEY (kauba_kategooria_kood) REFERENCES Kauba_kategooria (kauba_kategooria_kood) ON DELETE No Action ON UPDATE Cascade
)
;



CREATE SEQUENCE isik_isik_id_seq INCREMENT 1 START 1
;
